<!DOCTYPE html>
<html lang="{{ site.lang | default: 'en-US' }}">
<head>
  <meta charset="UTF-8">
  {% seo %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#157878">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap" as="style" type="text/css" crossorigin>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap" rel="stylesheet">

  <!-- Marked.js for Markdown parsing -->
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>

  <style>
    body {
      font-family: 'Open Sans', sans-serif;
      background-color: #f9f9f9;
      color: #333;
      margin: 0;
    }

    .page-header {
      text-align: center;
      padding: 60px 20px 40px;
      background: linear-gradient(135deg, #157878, #1abc9c);
      color: #fff;
    }

    .project-name {
      font-size: 2.5rem;
      font-weight: 700;
      margin-bottom: 10px;
    }

    .project-tagline {
      font-size: 1.2rem;
      font-weight: 400;
      margin-bottom: 30px;
      opacity: 0.9;
    }

    .btn {
      display: inline-block;
      margin: 5px 10px;
      padding: 10px 20px;
      background-color: rgba(255,255,255,0.2);
      color: #fff;
      border-radius: 30px;
      font-weight: 600;
      transition: all 0.3s ease;
      cursor: pointer;
    }

    .btn:hover {
      background-color: #fff;
      color: #157878;
    }

    .main-content {
      max-width: 900px;
      margin: 40px auto;
      padding: 0 20px;
    }

    .site-footer {
      text-align: center;
      padding: 30px 20px;
      background-color: #157878;
      color: #fff;
      font-size: 0.9rem;
      margin-top: 50px;
      border-top-left-radius: 20px;
      border-top-right-radius: 20px;
    }

    .site-footer a {
      color: #fff;
      font-weight: 600;
    }

    .site-footer a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>
  <header class="page-header" role="banner">
    <h1 class="project-name">{{ page.title | default: site.title | default: site.github.repository_name }}</h1>
    <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>

    <a id="mlButton" class="btn">Machine Learning</a>
    <a href="https://github.com/Kakparov91/e-Portfolio" class="btn">View on GitHub</a>
  </header>

  <main id="content" class="main-content" role="main">
    {{ content }}
  </main>

  <footer class="site-footer">
    {% if site.github.is_project_page %}
      <span class="site-footer-owner">
        <a href="{{ site.github.repository_url }}">{{ site.github.repository_name }}</a> 
        is maintained by <a href="{{ site.github.owner_url }}">{{ site.github.owner_name }}</a>.
      </span>
    {% endif %}
    <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
  </footer>

  <script>
    document.getElementById('mlButton').addEventListener('click', function(event) {
      event.preventDefault();

      fetch('ml.md')
        .then(response => {
          if (!response.ok) {
            throw new Error('Markdown file not found');
          }
          return response.text();
        })
        .then(data => {
          let htmlContent = marked.parse(data);
          document.getElementById('content').innerHTML = htmlContent;
        })
        .catch(error => {
          console.error('Error:', error);
          document.getElementById('content').innerHTML = '<p>Content could not be loaded.</p>';
        });
    });
  </script>
</body>
</html>
